version: "3"

services:
  app:
    build:
      context: node
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"

  db:
    #build:
    #  context: ./path
    #  dockerfile: Dockerfile
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - node-network

    ports:
      - "3306:3306"          
networks:
  node-network:
    driver: bridge